version: "3.8"
services:

  nginx:
    image: nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
    - 80:80
  
  client:
    image: client
    build:
        context: client
        dockerfile: ./Dockerfile
    container_name: client
    restart: unless-stopped
    ports:
      - 3000:3000

  api:
    image: api
    build:
        context: api
        dockerfile: ./Dockerfile
    container_name: server
    restart: unless-stopped
    ports:
      - 3001:3001

  mongodb:
    image: mongo:latest
    container_name: database
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pZ5FbOZ50GkZ
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
    driver: local
